#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
from pathlib import Path

import psycopg2
from psycopg2.extras import execute_values


HAN_RE = re.compile(r"[一-鿿]")


EXACT = {
    "新增": "Thêm mới",
    "人物关系": "Quan hệ nhân vật",
    "初十": "Mùng mười",
    "普通：": "Thường:",
    "论道结束！": "Luận đạo kết thúc!",
    "外防  {0}": "Ngoại phòng  {0}",
    "已关入牢房": "Đã tống vào lao",
    "简单": "Dễ",
    "打造类型": "Loại chế tạo",
    "完美：": "Hoàn mỹ:",
    "丑": "Xấu",
    "用于生活系统": "Dùng cho hệ thống sinh hoạt",
    "词条范围内的最大词条数": "Số dòng thuộc tính tối đa trong phạm vi",
    "【血气】类道具使用冷却中": "Vật phẩm loại [Huyết Khí] đang hồi",
    "悟卷 - {0}": "Ngộ quyển - {0}",
    "门派资金不足，无法购买": "Môn phái không đủ ngân quỹ, không thể mua",
    "并额外赋予：": "Và ban thêm:",
    "装备 - {0}": "Trang bị - {0}",
    "近": "Gần",
    "远": "Xa",
    "百分比": "Phần trăm",
    ",（容貌额外增加{0}）": ", (dung mạo tăng thêm {0})",
    "前置条件": "Điều kiện trước",
    "武林神话": "Võ Lâm Thần Thoại",
    "行动力不足": "Không đủ hành động lực",
    "天榜": "Thiên Bảng",
    "人榜": "Nhân Bảng",
    "成活率：": "Tỉ lệ sống:",
    "装备槽": "Ô trang bị",
    "精力不足": "Không đủ tinh lực",
    "请求失败:": "Yêu cầu thất bại:",
    "{0}个时辰{1}刻": "{0} canh giờ {1} khắc",
    "门派好感": "Thiện cảm môn phái",
    "成功": "Thành công",
    "当期物品已经售空": "Vật phẩm kỳ này đã bán hết",
    "使用属性点数调整战斗倾向属性。": "Dùng điểm thuộc tính để điều chỉnh thiên hướng chiến đấu.",
    "修炼所需物品不足": "Không đủ vật phẩm cần để tu luyện",
    "武学秘卷 - {0}": "Bí quyển võ học - {0}",
    "当前已选择后天天赋": "Hiện đã chọn thiên phú hậu thiên",
    "威力:": "Uy lực:",
    "限使用次数{0}次": "Giới hạn dùng {0} lần",
    "卫堂堂主": "Đường chủ Vệ Đường",
    "技能威力": "Uy lực kỹ năng",
    "该功能未开放，请大侠等正式版本": "Chức năng này chưa mở, xin đại hiệp chờ bản chính thức",
    "(材料2)": "(Nguyên liệu 2)",
    "概率未成功触发": "Xác suất chưa kích hoạt thành công",
    "相交意气": "Ý khí tương giao",
    "父亲": "Cha",
    "酒类": "Rượu",
    "本次修行结束，耗时": "Lần tu hành này kết thúc, tốn",
    "十八": "Mười tám",
    "当前门派正处于战争状态，无法亲征": "Môn phái hiện đang trong trạng thái chiến tranh, không thể thân chinh",
    "酿酒成功": "Ủ rượu thành công",
    "选择人物": "Chọn nhân vật",
    "确定要加入{0}？": "Xác nhận gia nhập {0}?",
    "解锁成功": "Mở khóa thành công",
    "你的酒太差了": "Rượu của ngươi quá tệ",
    "正在进入藏经阁": "Đang vào Tàng Kinh Các",
    "未": "Chưa",
    "拍卖期间不可挂牌": "Không thể treo bán trong lúc đấu giá",
    "结缘": "Kết duyên",
    "对方已是门下弟子": "Đối phương đã là đệ tử trong môn",
    "百": "Trăm",
    "门派管理员已满员": "Quản sự môn phái đã đầy",
    "按 {0} 离开": "Nhấn {0} để rời",
    "产出几率": "Tỉ lệ sản xuất",
    "请输入汉字内容": "Vui lòng nhập nội dung chữ Hán",
    "技能：{0}冷却中": "Kỹ năng: {0} đang hồi",
    "对话NpcId": "Đối thoại NpcId",
    "确认是否直接进入论辩": "Xác nhận vào luận biện ngay?",
    "是否需要保存更改并就此退出": "Có cần lưu thay đổi rồi thoát không?",
    "垂钓中": "Đang câu",
    "请选择一位主将": "Vui lòng chọn một chủ tướng",
    "失败：": "Thất bại:",
    "人字级杀手需要消耗：": "Sát thủ cấp Nhân cần tiêu hao:",
    "丹药：": "Đan dược:",
    "略有耳闻": "Có nghe qua",
    "长生剑fdasdasd": "Trường Sinh Kiếm fdasdasd",
    "女": "Nữ",
    "获得物品：": "Nhận vật phẩm:",
    "退出挑战": "Thoát khiêu chiến",
    "指点": "Chỉ điểm",
    "当前队伍为空，请先编辑队伍！": "Đội hiện trống, hãy chỉnh đội trước!",
    "请先建造门派大殿": "Hãy xây đại điện môn phái trước",
    "模组列表": "Danh sách mô-đun",
    "品质/等级：随机": "Phẩm chất/cấp: ngẫu nhiên",
    "一定要的话，就看运气了吧。": "Nếu nhất định muốn, vậy xem vận may đi.",
    "请先选择材料！": "Hãy chọn nguyên liệu trước!",
    "标题名称": "Tên tiêu đề",
    "猴": "Khỉ",
    "十二月": "Tháng mười hai",
    "最大鱼饵数：": "Số mồi câu tối đa:",
    "烹饪成功": "Nấu ăn thành công",
    "已经获得了交代物品": "Đã nhận vật phẩm bàn giao",
    "重命名": "Đổi tên",
    "精通 ": "Tinh thông ",
    "天下第一": "Thiên Hạ Đệ Nhất",
    "图标": "Biểu tượng",
    "（熟练）": "(thuần thục)",
    "完成了此信息的处理": "Đã xử lý xong thông tin này",
    "不能烹饪": "Không thể nấu ăn",
    "陆地神仙": "Lục Địa Thần Tiên",
    "新建项目": "Tạo mục mới",
    "潜行状态被解除": "Trạng thái tiềm hành đã bị giải trừ",
    "此物品已被拍下": "Vật phẩm này đã được đấu giá",
    "消耗精力": "Tiêu hao tinh lực",
    "钓鱼": "Câu cá",
    "踏浪行波": "Đạp Lãng Hành Ba",
    "降渊恒力·流火长阵": "Giáng Uyên Hằng Lực - Lưu Hỏa Trường Trận",
    "离莹·": "Ly Oánh -",
    "伶魁": "Linh Khôi",
    "闾丘": "Lư Khâu",
    "南宫": "Nam Cung",
}

EXACT.update({
    "戌": "Tuất",
    "肾": "Thận",
    "戊": "Mậu",
    "鼠": "Chuột",
    "脾": "Tỳ",
    "辛": "Tân",
    "母": "Mẹ",
    "七": "Bảy",
    "刃": "Nhận",
    "突": "Đột",
    "千": "Nghìn",
    "八": "Tám",
    "辰": "Thìn",
    "卯": "Mão",
    "水": "Thủy",
    "决": "Quyết",
    "亿": "Ức",
    "新": "Mới",
    "和": "Và",
    "天": "Thiên",
    "及": "Và",
    "短": "Ngắn",
    "男": "Nam",
    "肝": "Can",
    "午": "Ngọ",
    "羊": "Dê",
    "长": "Dài",
    "奇": "Kỳ",
    "赏": "Thưởng",
    "破": "Phá",
    "乙": "Ất",
    "组": "Nhóm",
    "壬": "Nhâm",
    "庚": "Canh",
    "土": "Thổ",
    "掌": "Chưởng",
    "大": "Lớn",
    "申": "Thân",
    "癸": "Quý",
    "木": "Mộc",
    "委": "Ủy thác",
    "己": "Kỷ",
    "公": "Công",
    "主": "Chính",
    "丁": "Đinh",
    "低": "Thấp",
    "高": "Cao",
    "我": "Ta",
    "亥": "Hợi",
    "支": "Nhánh",
    "龙": "Long",
    "丙": "Bính",
    "五": "Năm",
    "火": "Hỏa",
    "九": "Chín",
    "蛇": "Rắn",
    "肺": "Phế",
    "万": "Vạn",
    "十": "Mười",
    "击": "Kích",
    "蛊缠": "Cổ Triền",
    "蚀骨": "Thực Cốt",
    "价格": "Giá",
    "配偶": "Phối ngẫu",
    "方向": "Phương hướng",
    "女儿": "Con gái",
    "月痕": "Nguyệt Ngân",
    "淡墨": "Đạm Mặc",
    "欧阳": "Âu Dương",
    "纳贤": "Nạp hiền",
    "以上": "Trở lên",
    "闲聊": "Tán gẫu",
    "商场": "Cửa hàng",
    "初二": "Mùng hai",
    "气运": "Khí vận",
    "极长": "Cực dài",
    "[上": "[Trên",
    "待命": "Chờ lệnh",
    "不足": "Không đủ",
    "加速": "Tăng tốc",
    "廿二": "Hai mươi hai",
    "重铸": "Đúc lại",
    "发展": "Phát triển",
    "位置": "Vị trí",
    "转向": "Chuyển hướng",
    "姐妹": "Tỷ muội",
    "单于": "Thiền Vu",
    "兵学": "Binh học",
    "行动": "Hành động",
    "太叔": "Thái Thúc",
    "脱下": "Cởi ra",
    "问答": "Hỏi đáp",
    "十四": "Mười bốn",
    "岩魂": "Nham Hồn",
    "音频": "Âm thanh",
    "总舵": "Tổng đà",
    "认罪": "Nhận tội",
    "铁躯": "Thiết Khu",
    "淳于": "Thuần Vu",
    "紫色": "Tím",
    "十五": "Mười lăm",
    "瘴噬": "Chướng Phệ",
    "宇文": "Vũ Văn",
    "不用": "Không cần",
    "冥邃": "Minh Toại",
    "绿色": "Xanh lục",
    "廿三": "Hai mươi ba",
    "皇甫": "Hoàng Phủ",
    "徒弟": "Đồ đệ",
    "书法": "Thư pháp",
    "遁玄": "Độn Huyền",
    "连斩": "Liên trảm",
    "初一": "Mùng một",
    "初八": "Mùng tám",
    "对饮": "Đối ẩm",
    "二月": "Tháng hai",
    "距离": "Khoảng cách",
    "更多": "Thêm",
    "人数": "Số người",
    "学会": "Học được",
    "极高": "Cực cao",
    "威望": "Uy vọng",
    "韧志": "Nhẫn chí",
    "子车": "Tử Xa",
    "三月": "Tháng ba",
    "司徒": "Tư Đồ",
    "炒制": "Xào chế",
    "初三": "Mùng ba",
    "慕容": "Mộ Dung",
    "十一": "Mười một",
    "打猎": "Săn bắn",
    "驯化": "Thuần hóa",
    "诸葛": "Gia Cát",
    "加入": "Gia nhập",
    "靖延": "Tĩnh Diên",
    "金色": "Vàng kim",
    "身体": "Thân thể",
    "头发": "Tóc",
    "曦光": "Hi Quang",
    "仇人": "Kẻ thù",
    "下架": "Gỡ khỏi kệ",
    "正邪": "Chính tà",
    "廿九": "Hai mươi chín",
    "炽烨": "Sí Diệp",
    "乐正": "Nhạc Chính",
    "技业": "Kỹ nghiệp",
    "未知": "Chưa biết",
    "令狐": "Lệnh Hồ",
    "巧取": "Khéo đoạt",
    "困难": "Khó",
    "售价": "Giá bán",
    "姊妹": "Tỷ muội",
    "上刑": "Dùng hình",
    "公西": "Công Tây",
    "击杀": "Giết",
    "连招": "Liên chiêu",
    "初七": "Mùng bảy",
    "初九": "Mùng chín",
    "灌注": "Quán chú",
    "十月": "Tháng mười",
    "段:": "Đoạn:",
    "阶段": "Giai đoạn",
    "时辰": "Canh giờ",
    "红牌": "Thẻ đỏ",
    "五月": "Tháng năm",
    "焚天": "Phần Thiên",
    "打败": "Đánh bại",
    "战胜": "Chiến thắng",
    "君辞": "Quân Từ",
    "辨矿": "Biện khoáng",
    "脚本": "Script",
    "若纱": "Nhược Sa",
    "进阶": "Tiến cấp",
    "夏侯": "Hạ Hầu",
    "拓跋": "Thác Bạt",
    "雪练": "Tuyết Luyện",
    "售出": "Đã bán",
    "替換": "Thay thế",
    "全局": "Toàn cục",
    "复制": "Sao chép",
    "待定": "Chờ định",
    "免费": "Miễn phí",
    "头牌": "Hoa khôi",
    "示意": "Ra hiệu",
    "清明": "Thanh Minh",
    "保留": "Giữ lại",
    "朋友": "Bằng hữu",
    "知己": "Tri kỷ",
    "东方": "Đông Phương",
    "廿六": "Hai mươi sáu",
    "劫杀": "Cướp giết",
    "廿八": "Hai mươi tám",
    "算了": "Thôi vậy",
    "拜师": "Bái sư",
    "蝎锋": "Hạt Phong",
    "对话": "Đối thoại",
    "廿四": "Hai mươi bốn",
    "廿五": "Hai mươi lăm",
    "极难": "Cực khó",
    "车夫": "Phu xe",
    "忘川": "Vong Xuyên",
    "炎鸿": "Viêm Hồng",
    "扶风": "Phù Phong",
    "下阵": "Rút khỏi trận",
    "酿造": "Ủ rượu",
    "红色": "Đỏ",
    "肆腐": "Tứ Hủ",
    "巫毒": "Vu độc",
    "掉落": "Rơi",
    "阳佟": "Dương Đồng",
    "公开": "Công khai",
    "五脏": "Ngũ tạng",
    "伴侣": "Bạn đời",
    "加赛": "Đấu thêm",
    "旧雪": "Cựu Tuyết",
    "作者": "Tác giả",
    "亲征": "Thân chinh",
    "败：": "Bại:",
    "无情": "Vô tình",
    "卫堂": "Vệ Đường",
    "术法": "Thuật pháp",
    "炙曜": "Chích Diệu",
    "滑动": "Trượt",
    "流逸": "Lưu Dật",
    "效果": "Hiệu quả",
    "复赛": "Vòng phục đấu",
    "吊坠": "Mặt dây",
    "药品": "Dược phẩm",
    "巨大": "Cực lớn",
    "烈焱": "Liệt Diễm",
    "时间": "Thời gian",
    "地榜": "Địa Bảng",
    "医道": "Y đạo",
    "西门": "Tây Môn",
    "大型": "Cỡ lớn",
    "情谊": "Tình nghĩa",
    "地狱": "Địa ngục",
    "自身": "Bản thân",
    "四月": "Tháng tư",
    "苍炙": "Thương Chích",
    "寅": "Dần",
    "巫马": "Vu Mã",
    "谷粱": "Cốc Lương",
    "缝纫": "May vá",
    "正月": "Tháng giêng",
    "霸意": "Bá Ý",
    "儿子": "Con trai",
    "下马": "Xuống ngựa",
    "燕迹": "Yến Tích",
    "多丢": "Đa Đâu",
    "十九": "Mười chín",
    "索要": "Đòi lấy",
    "虎魄": "Hổ Phách",
    "评分": "Điểm đánh giá",
    "辞忧": "Từ Ưu",
    "归海": "Quy Hải",
    "以下": "Trở xuống",
    "烬辉": "Tẫn Huy",
    "百里": "Bách Lý",
    "鲜于": "Tiên Vu",
    "司空": "Tư Không",
    "十七": "Mười bảy",
    "传简": "Truyền giản",
    "轩辕": "Hiên Viên",
    "小于": "Nhỏ hơn",
    "左丘": "Tả Khâu",
    "辞风": "Từ Phong",
    "咏寞": "Vịnh Mịch",
    "槿瑟": "Cận Sắt",
    "三十": "Ba mươi",
    "灼煜": "Chước Dục",
    "音律": "Âm luật",
    "秘诀": "Bí quyết",
    "上马": "Lên ngựa",
    "十三": "Mười ba",
    "化神": "Hóa Thần",
    "食物": "Thức ăn",
    "煞影": "Sát Ảnh",
    "和棋": "Hòa cờ",
    "上官": "Thượng Quan",
    "十六": "Mười sáu",
    "五行": "Ngũ hành",
    "礼堂": "Lễ Đường",
    "论辩": "Luận biện",
    "冥王": "Minh Vương",
    "九月": "Tháng chín",
    "大于": "Lớn hơn",
    "廿七": "Hai mươi bảy",
    "好友": "Hảo hữu",
    "尉迟": "Uất Trì",
    "金币": "Vàng",
    "横戈": "Hoành Qua",
    "增加": "Tăng",
    "师父": "Sư phụ",
    "礼物": "Quà",
    "喂食": "Cho ăn",
    "东郭": "Đông Quách",
    "司马": "Tư Mã",
    "决赛": "Chung kết",
    "本地": "Cục bộ",
    "空格": "Khoảng trắng",
    "耗材": "Vật tư tiêu hao",
    "诡学": "Quỷ Học",
    "护甲": "Hộ giáp",
    "烟柳": "Yên Liễu",
    "侵魂": "Xâm Hồn",
    "形状": "Hình dạng",
    "会心": "Hội tâm",
    "降低": "Giảm",
    "清丝": "Thanh Ti",
    "中等": "Trung bình",
    "小型": "Cỡ nhỏ",
    "密卷": "Mật quyển",
    "达到": "Đạt",
    "公冶": "Công Dã",
    "奇术": "Kỳ thuật",
    "订阅": "Theo dõi",
    "自建": "Tự tạo",
    "春水": "Xuân Thủy",
    "贿赂": "Hối lộ",
    "临月": "Lâm Nguyệt",
    "勒索": "Tống tiền",
    "名称": "Tên",
    "贤堂": "Hiền Đường",
    "寂韵": "Tịch Vận",
    "廿一": "Hai mươi mốt",
    "红颜": "Hồng nhan",
    "已故": "Đã mất",
    "初五": "Mùng năm",
    "呼延": "Hô Diên",
    "制作": "Chế tác",
    "比斗": "Tỉ đấu",
    "幽寥": "U Liêu",
    "彩色": "Có màu",
    "点击": "Nhấn",
    "更名": "Đổi tên",
    "胜：": "Thắng:",
    "强化": "Cường hóa",
    "我:": "Ta:",
    "放下": "Đặt xuống",
    "巧匠": "Xảo Tượng",
    "叱干": "Sất Can",
    "二十": "Hai mươi",
    "长孙": "Trưởng Tôn",
    "遗忘": "Quên",
    "隐梦": "Ẩn Mộng",
    "濮阳": "Bộc Dương",
    "影密": "Ảnh Mật",
    "毒技": "Độc kỹ",
    "凌云": "Lăng Vân",
    "伯赏": "Bá Thưởng",
    "云收": "Vân Thu",
    "坊堂": "Phường Đường",
    "初四": "Mùng bốn",
    "弟子": "Đệ tử",
    "贯虹": "Quán Hồng",
    "劲势": "Kình thế",
    "雅正": "Nhã Chính",
    "初学": "Sơ học",
    "烟渺": "Yên Miểu",
    "余笙": "Dư Sênh",
    "七月": "Tháng bảy",
    "寒潜": "Hàn Tiềm",
    "初六": "Mùng sáu",
    "财堂": "Tài Đường",
    "蜒舞": "Diên Vũ",
    "比较": "So sánh",
    "分配": "Phân phối",
    "不敌": "Không địch nổi",
    "【主】": "[Chủ]",
    "线索：": "Manh mối:",
    "秘籍组": "Nhóm bí tịch",
    "未达成": "Chưa đạt",
    "你赢了": "Ngươi thắng",
    "坚韧：": "Kiên nhẫn:",
    "你输了": "Ngươi thua",
    "第一式": "Thức thứ nhất",
    "最大值": "Giá trị tối đa",
    "金币：": "Vàng:",
    "目标1": "Mục tiêu 1",
    "精巧：": "Tinh xảo:",
    "装备:": "Trang bị:",
    "2进1": "2 vào 1",
    "价格：": "Giá:",
    "答错~": "Đáp sai~",
    "未拥有": "Chưa sở hữu",
    "触发器": "Trigger",
    "素材:": "Nguyên liệu:",
    "游墙术": "Du Tường Thuật",
    "雁行决": "Nhạn Hành Quyết",
    "酿酒谱": "Phổ ủ rượu",
    "洗练:": "Tẩy luyện:",
    "已领取": "Đã nhận",
    "未学习": "Chưa học",
    "订阅数": "Số theo dõi",
    "轻功值": "Khinh công",
    "特殊：": "Đặc biệt:",
    "收入：": "Thu nhập:",
    "8进4": "8 vào 4",
    "道具 ": "Đạo cụ ",
    "注意：": "Chú ý:",
    "脚本 ": "Script ",
    "执行中": "Đang thực thi",
    "未分配": "Chưa phân phối",
    "门派：": "Môn phái:",
    "【奇】": "[Kỳ]",
    "未领悟": "Chưa lĩnh ngộ",
    "左护法": "Tả hộ pháp",
    "角色 ": "Vai trò ",
    "使用后": "Sau khi dùng",
    "全达成": "Đạt toàn bộ",
    "【谜】": "[Mê]",
    "来源：": "Nguồn:",
    "副宗主": "Phó tông chủ",
    "当前：": "Hiện tại:",
    "确定键": "Phím xác nhận",
    "未参悟": "Chưa tham ngộ",
    "大长老": "Đại trưởng lão",
    "【支】": "[Nhánh]",
    "专精 ": "Chuyên tinh ",
    "悬赏榜": "Bảng treo thưởng",
    "未加入": "Chưa gia nhập",
    "技艺书": "Sách kỹ nghệ",
    "无名氏": "Vô danh thị",
    "劣质：": "Kém:",
    "道具：": "Đạo cụ:",
    "花费：": "Chi phí:",
    "未学会": "Chưa học được",
    "下一页": "Trang sau",
    "无描述": "Không mô tả",
    "不保存": "Không lưu",
    "售价：": "Giá bán:",
    "拥有：": "Sở hữu:",
    "半决赛": "Bán kết",
    "种植中": "Đang trồng",
    "可攻击": "Có thể tấn công",
    "激活：": "Kích hoạt:",
    "属性点": "Điểm thuộc tính",
    "道具:": "Đạo cụ:",
    "条件组": "Nhóm điều kiện",
    "时限：": "Thời hạn:",
    "用于@": "Dùng cho @",
    "需要：": "Cần:",
    "已购买": "Đã mua",
    "比例值": "Giá trị tỉ lệ",
    "文件名": "Tên file",
    "固定值": "Giá trị cố định",
    "已进阶": "Đã tiến cấp",
    "最小值": "Giá trị tối thiểu",
    "书卷:": "Thư quyển:",
    "词条组": "Nhóm thuộc tính",
    "了结他": "Kết liễu hắn",
    "无暇：": "Vô hạ:",
    "降低至": "Giảm xuống",
    "炼丹谱": "Phổ luyện đan",
    "崔牧之": "Thôi Mục Chi",
    "提示：": "Gợi ý:",
    "十字键": "Phím chữ thập",
    "4进2": "4 vào 2",
    "物品:": "Vật phẩm:",
    "秘籍：": "Bí tịch:",
    "要求值": "Giá trị yêu cầu",
    "未达到": "Chưa đạt",
    "上一页": "Trang trước",
    "目标2": "Mục tiêu 2",
    "十一月": "Tháng mười một",
    "无秘药": "Không có bí dược",
    "天赋槽": "Ô thiên phú",
    "休息中": "Đang nghỉ",
    "烹饪谱": "Phổ nấu ăn",
    "蓄伤:": "Tích thương:",
    "精英怪": "Tinh anh quái",
    "已解锁": "Đã mở khóa",
    "巧手谱": "Phổ Xảo Thủ",
    "争夺擂": "Lôi đài tranh đoạt",
    "未卜·": "Vị Bốc -",
    "上手 ": "Nhập môn ",
    "战好·": "Chiến Hảo -",
    "扶山·": "Phù Sơn -",
    "已完成": "Đã hoàn thành",
    "提升至": "Tăng lên",
    "可获得": "Có thể nhận",
    " 掌门": " Chưởng môn",
    "熟练 ": "Thuần thục ",
    "草上飞": "Thảo Thượng Phi",
    "耗时：": "Tốn thời gian:",
    "入门 ": "Nhập môn ",
    "经脉:": "Kinh mạch:",
    "登堂入室": "Đăng đường nhập thất",
    "可以缝纫": "Có thể may vá",
    "需要道具": "Cần đạo cụ",
    "突破瓶颈": "Đột phá bình cảnh",
    "一方豪杰": "Hào kiệt một phương",
    "来源描述": "Mô tả nguồn",
    "没有种子": "Không có hạt giống",
    "模型比例": "Tỉ lệ mô hình",
    "技能Id": "Skill ID",
    "商店组 ": "Nhóm cửa hàng ",
    "请求失败": "Yêu cầu thất bại",
    "基础配置": "Cấu hình cơ bản",
    "鼠标右键": "Chuột phải",
    "耳朵宽度": "Độ rộng tai",
    "江湖初识": "Sơ thức giang hồ",
    "金钱不足": "Không đủ tiền",
    "下巴前后": "Cằm trước-sau",
    "暗杀指派": "Chỉ phái ám sát",
    "任务类型": "Loại nhiệm vụ",
    "备注信息": "Thông tin ghi chú",
    "出现过。": "Đã từng xuất hiện.",
    "基础信息": "Thông tin cơ bản",
    "首次效果": "Hiệu quả lần đầu",
    "偏僻区域": "Khu vực hẻo lánh",
    "自动脚本": "Script tự động",
    "悟道识性": "Ngộ đạo thức tính",
    "药品不足": "Không đủ dược phẩm",
    "开始上传": "Bắt đầu tải lên",
    "籍籍无名": "Vô danh tiểu tốt",
    "形如路人": "Trông như người qua đường",
    "鼻子挺拔": "Mũi cao thẳng",
    "建筑收益": "Lợi tức kiến trúc",
    "生死仇敌": "Sinh tử cừu địch",
    "消耗金钱": "Tiêu hao tiền",
    "可以酿酒": "Có thể ủ rượu",
    "领取俸禄": "Nhận bổng lộc",
    "代为巧手": "Làm xảo thủ thay",
    "镜头追踪": "Theo dõi camera",
    "互通名姓": "Trao đổi danh tính",
    "材料属性": "Thuộc tính nguyên liệu",
    "改变属性": "Đổi thuộc tính",
    "词条组 ": "Nhóm thuộc tính ",
    "创建联盟": "Tạo liên minh",
    "上传失败": "Tải lên thất bại",
    "覆写成功": "Ghi đè thành công",
    "凌空踏虚": "Lăng Không Đạp Hư",
    "属性比例": "Tỉ lệ thuộc tính",
    "勒索成功": "Tống tiền thành công",
    "武学功法": "Võ học công pháp",
    "装备品级": "Phẩm cấp trang bị",
    "修炼相关": "Liên quan tu luyện",
    "真气不足": "Không đủ chân khí",
    "人物五行": "Ngũ hành nhân vật",
    "感悟不足": "Không đủ cảm ngộ",
    "战斗脚本": "Script chiến đấu",
    "喂食成功": "Cho ăn thành công",
    "售卖个数": "Số lượng bán",
    "财堂堂主": "Đường chủ Tài Đường",
    "烹饪材料": "Nguyên liệu nấu ăn",
    "稍后考虑": "Suy xét sau",
    "困难提示": "Gợi ý khó",
    "耳朵上下": "Tai trên-dưới",
    "模组制作": "Chế tác mô-đun",
    "登录失效": "Đăng nhập hết hiệu lực",
    "索要数量": "Số lượng yêu cầu",
    "完成悬赏": "Hoàn thành treo thưởng",
    "是否开源": "Có mở nguồn không?",
    "确认选择": "Xác nhận lựa chọn",
    "鼻梁上下": "Sống mũi trên-dưới",
    "灌注成功": "Quán chú thành công",
    "光标悬浮": "Di chuột",
    "秘法选择": "Chọn bí pháp",
    "血海深仇": "Huyết hải thâm cừu",
    "提升成功": "Tăng thành công",
    "相见恨晚": "Gặp nhau quá muộn",
    " 右护法": " Hữu hộ pháp",
    "(长按)": "(nhấn giữ)",
    "生平描述": "Mô tả thân thế",
    "解锁描述": "Mô tả mở khóa",
    "成员列表": "Danh sách thành viên",
    "身份未知": "Thân phận chưa rõ",
    "眼睛深浅": "Độ sâu mắt",
    "成功率：": "Tỉ lệ thành công:",
    "容我想想": "Để ta nghĩ đã",
    "售卖道具": "Bán đạo cụ",
    "门派传功": "Truyền công môn phái",
    "新建查询": "Tạo truy vấn mới",
    "有所挑战": "Có chút thử thách",
    "技能ID": "Skill ID",
    "好感度:": "Độ thiện cảm:",
    "深恶痛绝": "Căm ghét tận xương",
    "无所不谈": "Không gì không nói",
    "任务链 ": "Chuỗi nhiệm vụ ",
    "进入游戏": "Vào game",
    "取消显示": "Hủy hiển thị",
    "详细配置": "Cấu hình chi tiết",
    "银子不够": "Không đủ bạc",
    "操作成功": "Thao tác thành công",
    "门派商店": "Cửa hàng môn phái",
    "编译脚本": "Biên dịch script",
    "招募队友": "Chiêu mộ đồng đội",
    "按下D键": "Nhấn phím D",
    "积分: ": "Điểm: ",
    "驻扎待命": "Đóng quân chờ lệnh",
    "三流武学": "Võ học tam lưu",
    "已重置！": "Đã đặt lại!",
    "豪杰天骄": "Hào kiệt thiên kiêu",
    "堆叠上限": "Giới hạn cộng dồn",
    "携带金钱": "Tiền mang theo",
    "最小属性": "Thuộc tính tối thiểu",
    "{0}时": "{0} giờ",
    "耳垂长度": "Độ dài dái tai",
    "未知线索": "Manh mối chưa rõ",
    "稍显棘手": "Hơi khó xử",
    "尚不知晓": "Chưa biết",
    "密码错误": "Sai mật khẩu",
    "非常简单": "Rất dễ",
    "下巴宽度": "Độ rộng cằm",
    "挂牌成功": "Treo bán thành công",
    "武道宗师": "Võ Đạo Tông Sư",
    "真气上限": "Giới hạn chân khí",
    "巧手失败": "Xảo thủ thất bại",
    "代为炼丹": "Luyện đan thay",
    "（化境）": "(hóa cảnh)",
    "眉中左右": "Giữa mày trái-phải",
    "是否完成": "Đã hoàn thành chưa?",
    "炼丹成功": "Luyện đan thành công",
    "最多订阅": "Theo dõi tối đa",
    "代为缝纫": "May vá thay",
    "本地模组": "Mô-đun cục bộ",
    "放人离去": "Thả người rời đi",
    "视如寇仇": "Xem như thù địch",
    "抢夺绝学": "Cướp đoạt tuyệt học",
    "目标描述": "Mô tả mục tiêu",
    "战斗准备": "Chuẩn bị chiến đấu",
    "对话ID": "Dialogue ID",
    "经典模式": "Chế độ kinh điển",
    "能否出售": "Có thể bán không?",
    "延迟时间": "Thời gian trễ",
    "快捷栏一": "Thanh nhanh 1",
    "背包已满": "Túi đã đầy",
    "不能缝纫": "Không thể may vá",
    "所有等级": "Mọi cấp",
    "悬赏解密": "Giải mật treo thưởng",
    "下巴上下": "Cằm trên-dưới",
    "确认放弃": "Xác nhận từ bỏ",
    "删除成功": "Xóa thành công",
    "成长属性": "Thuộc tính trưởng thành",
    "燕国百姓": "Bách tính nước Yên",
    "提供者：": "Người cung cấp:",
    "{0}日": "{0} ngày",
    "y轴向上": "Trục y hướng lên",
    "巧手材料": "Nguyên liệu xảo thủ",
    "不能巧手": "Không thể xảo thủ",
    "宗门大比": "Đại bỉ tông môn",
    "武学秘籍": "Bí tịch võ học",
    "眉毛内外": "Lông mày trong-ngoài",
    "八拜之交": "Bát bái chi giao",
    "是否删除": "Có xóa không?",
    "不能炼制": "Không thể luyện chế",
    "选择词条": "Chọn thuộc tính",
    "略通拳脚": "Sơ thông quyền cước",
    "首杀掉落": "Rơi khi hạ đầu tiên",
    "说服入派": "Thuyết phục nhập phái",
    "十字键右": "Phím chữ thập phải",
    "可以烹饪": "Có thể nấu ăn",
    "套用外观": "Áp dụng ngoại hình",
    "道具小类": "Tiểu loại đạo cụ",
    "目标道具": "Đạo cụ mục tiêu",
    "当前血量": "Máu hiện tại",
    "拥有道具": "Có đạo cụ",
    "水火不容": "Thủy hỏa bất dung",
    "模组标签": "Nhãn mô-đun",
    "可见状态": "Trạng thái hiển thị",
    "登录成功": "Đăng nhập thành công",
    "锻造失败": "Đúc thất bại",
    "条件类型": "Loại điều kiện",
    "最大精力": "Tinh lực tối đa",
    "耐久: ": "Độ bền: ",
    "确认结束": "Xác nhận kết thúc",
    "y轴向下": "Trục y hướng xuống",
    "失去效果": "Mất hiệu quả",
    "签名错误": "Lỗi chữ ký",
    "（精通）": "(tinh thông)",
    "经脉武学": "Võ học kinh mạch",
    "领悟获得": "Lĩnh ngộ nhận được",
    "取消订阅": "Hủy theo dõi",
    "任务指引": "Chỉ dẫn nhiệm vụ",
    "鼻骨高低": "Độ cao xương mũi",
    "注册失败": "Đăng ký thất bại",
    "能力值：": "Giá trị năng lực:",
})


FACE_PARTS = {
    "嘴巴": "Miệng",
    "上唇": "môi trên",
    "下唇": "môi dưới",
    "嘴角": "khóe miệng",
    "眼睛": "mắt",
    "眼球": "nhãn cầu",
    "眼白": "lòng trắng mắt",
    "瞳孔": "đồng tử",
    "眉毛": "lông mày",
    "眉尾": "đuôi mày",
    "皮肤": "da",
    "肤色": "màu da",
    "发色": "màu tóc",
    "发型": "kiểu tóc",
    "唇色": "màu môi",
    "眼影": "phấn mắt",
    "眼线": "kẻ mắt",
    "纹身": "hình xăm",
    "妆容": "trang điểm",
    "下颌": "hàm dưới",
    "颧骨": "gò má",
    "脸颊": "má",
    "耳尖": "chóp tai",
    "光泽": "độ bóng",
    "浓淡": "đậm nhạt",
    "浓密": "độ rậm",
    "大小": "kích cỡ",
    "亮度": "độ sáng",
    "宽度": "độ rộng",
    "长度": "độ dài",
    "厚度": "độ dày",
    "饱满": "độ đầy",
    "角度": "góc",
    "左右": "trái-phải",
    "上下": "trên-dưới",
    "前后": "trước-sau",
    "两侧": "hai bên",
    "内": "trong",
    "中": "giữa",
}


def database_url() -> str:
    config = Path(".codex/config.toml").read_text(encoding="utf-8")
    match = re.search(r'^DATABASE_URI = "(.*)"', config, re.M)
    if not match:
        raise SystemExit("Missing database URL")
    return match.group(1)


def translate_face_slider(source: str) -> str | None:
    s = source.replace("（mirrored）", " (đối xứng)").replace("(mirrored)", " (đối xứng)")
    suffix = ""
    if s.endswith(" (đối xứng)"):
        s = s[: -len(" (đối xứng)")]
        suffix = " (đối xứng)"
    tokens: list[str] = []
    i = 0
    keys = sorted(FACE_PARTS, key=len, reverse=True)
    while i < len(s):
        if s[i].isdigit():
            j = i + 1
            while j < len(s) and s[j].isdigit():
                j += 1
            tokens.append(s[i:j])
            i = j
            continue
        matched = None
        for key in keys:
            if s.startswith(key, i):
                matched = key
                break
        if matched is None:
            return None
        tokens.append(FACE_PARTS[matched])
        i += len(matched)
    if not tokens:
        return None
    text = " ".join(tokens)
    return text[:1].upper() + text[1:] + suffix


def translate(source: str) -> str | None:
    if source in EXACT:
        return EXACT[source]

    face = translate_face_slider(source)
    if face:
        return face

    patterns: list[tuple[str, str]] = [
        (r"^<color=<TEMP_SPLIT>ff9758>限购 </color>\{0\}/\{1\}$", "<color=<TEMP_SPLIT>ff9758>Giới hạn mua </color>{0}/{1}"),
        (r"^<color=<TEMP_SPLIT>b09871>画</color>\{0\}$", "<color=<TEMP_SPLIT>b09871>Họa</color>{0}"),
        (r"^<color=<TEMP_SPLIT>ffffff>善恶值改变:</color> ×\{0\}$", "<color=<TEMP_SPLIT>ffffff>Thiện ác thay đổi:</color> ×{0}"),
        (r"^<color=<TEMP_SPLIT>F23B3B>注意： </color><color=<TEMP_SPLIT>FFE467>\{0\}</color>$", "<color=<TEMP_SPLIT>F23B3B>Chú ý: </color><color=<TEMP_SPLIT>FFE467>{0}</color>"),
        (r"^技能冷却  \{0\}秒$", "Hồi chiêu kỹ năng  {0}s"),
        (r"^限使用次数\{0\}次$", "Giới hạn dùng {0} lần"),
    ]
    for pattern, value in patterns:
        if re.match(pattern, source):
            return value
    return None


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--limit", type=int, default=1000)
    args = parser.parse_args()

    with psycopg2.connect(database_url()) as conn, conn.cursor() as cur:
        cur.execute(
            """
            select distinct on (tv.id) tv.id, tv.source_text
            from translation_values tv
            join translation_occurrences toc on toc.translation_value_id = tv.id
            join db_fields df on df.id = toc.db_field_id
            join db_lines dl on dl.id = df.line_id
            join db_sections ds on ds.id = dl.section_id
            where tv.status = 'pending'
              and ds.name = 'local_text_string'
              and df.field_index = 2
            order by tv.id
            """
        )
        updates: list[tuple[int, str]] = []
        for row_id, source in cur.fetchall():
            translated = translate(source)
            if translated is None or HAN_RE.search(translated):
                continue
            updates.append((row_id, translated))
            if len(updates) >= args.limit:
                break

        if updates:
            execute_values(
                cur,
                """
                update translation_values tv
                set translated_text = data.translated_text,
                    status = 'reviewed',
                    updated_at = now()
                from (values %s) as data(id, translated_text)
                where tv.id = data.id and tv.status = 'pending'
                """,
                updates,
            )
        print(f"attempted {len(updates)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
